### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by gpakosz** [CyberShadow/verysleepy#7]
Just tried to launch Very Sleepy CS on Windows 8.1 64bit.

I'm getting an error dialog saying:

    The procedure entry point SetCheckUserInterruptShared could not be located in the dynamic link library C:\WINDOWS\SYSTEM32\dbgeng.dll

Oddly enough, `verysleepy_0_82.exe` from which you forked works.

**Comment by CyberShadow** [comment]
It looks like I had already fixed this problem in the then-upcoming v0.90 (by renaming our `dbghelp.dll` to `dbghelpms.dll`) by the time this issue was opened (commit c4b9a500920ac9317e90ab115fc172723eb7a373). I must have forgotten that I fixed it. I'm guessing you were using v0.83, which still had the problem.

Please try the latest version, and feel free to reopen if this problem occurs again.
